### ISSUE TITLE
I can not convert the keras - retinanet.h5 model to tensorflow Pb model ,thanks.

### ISSUE THREAD

**Issue by zhang92** [amir-abdi/keras_to_tensorflow#17]
File "/home/zhangliyuan/RetinaNet/keras_to_tensorflow.py", line 54, in <module>
    net_model = load_model(weight_file_path)
  File "/home/zhangliyuan/.local/lib/python3.6/site-packages/keras/models.py", line 240, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/zhangliyuan/.local/lib/python3.6/site-packages/keras/models.py", line 314, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/home/zhangliyuan/.local/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/zhangliyuan/.local/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 140, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/zhangliyuan/.local/lib/python3.6/site-packages/keras/engine/topology.py", line 2490, in from_config
    process_layer(layer_data)
  File "/home/zhangliyuan/.local/lib/python3.6/site-packages/keras/engine/topology.py", line 2476, in process_layer
    custom_objects=custom_objects)
  File "/home/zhangliyuan/.local/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/zhangliyuan/.local/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 142, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/home/zhangliyuan/.local/lib/python3.6/site-packages/keras/engine/topology.py", line 1253, in from_config
    return cls(**config)
  File "/home/zhangliyuan/.local/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/zhangliyuan/.local/lib/python3.6/site-packages/keras/layers/normalization.py", line 71, in __init__
    super(BatchNormalization, self).__init__(**kwargs)
  File "/home/zhangliyuan/.local/lib/python3.6/site-packages/keras/engine/topology.py", line 280, in __init__
    raise TypeError('Keyword argument not understood:', kwarg)
TypeError: ('Keyword argument not understood:', 'freeze')

**Comment by amir-abdi** [comment]
What version of Tensorflow and Keras are you using?
From the looks of it, your error is in load_model; thus I assume the keras version used to train the model is different from the version running on your system right now.

**Comment by zhang92** [comment]
now i can convert keras-models to tensorflow pb. but this .pb model can't be used.  i use it to detecte.
Traceback (most recent call last):
  File "demo1.py", line 66, in <module>
    detecotr.detect(image)
  File "demo1.py", line 39, in detect
    image_tensor = self.detection_graph.get_tensor_by_name('image_tensor:0')
  File "/home/zly/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3207, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/home/zly/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3035, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/zly/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3077, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'image_tensor:0' refers to a Tensor which does not exist. The operation, 'image_tensor', does not exist in the graph."

**Comment by amir-abdi** [comment]
You are sending the wrong variable name: image_tensor:0
Check the ascii file of graphdef for the correct variable/operation name.

**Comment by zhang92** [comment]
thank you. I try it again

**Comment by zhudaoruyi** [comment]
@zhang92 
```
parser.add_argument('-graph_def', action="store", 
                    dest='graph_def', type=bool, default=False)
```

`python3 keras_to_tensorflow.py -input_model_file model.h5 -output_model_file model.pb -graph_def True`

Then, you can open "model.ascii" file and you can see the input layer's name,the default name is input_1:0

**Comment by amir-abdi** [comment]
I'll mark this as closed. 
Reopen if the issue persists.

**Comment by nickguimaraes** [comment]
Hello, I'm facing a very similar problem.

I've converted a .h5 to .pb file but I cannot do inference because I could only specify the input node name (input_1).

To test my model.pb I need to provide all of these tensor names,

image_tensor = input_1
detection_boxes = ?
detection_scores = ?
detection_classes = ?
num_detections = ?

otherwise the camera opens but as soon as it detects my object it crashes since it can't output the class_name, score...

I have described my problem in a bit more detail here,
https://github.com/fizyr/keras-retinanet/issues/874#issue-400091930

Also, this is a link for my graph. 
https://drive.google.com/open?id=1IXtSH9Y_LQk6LZ7iVXf9GjGY1KebaaUY

It's not very clear to me which nodes in my graph will store and return this information. 

I would appreciate if someone could help me understanding this. Thank you in advance.

**Comment by amir-abdi** [comment]
I checked your .pbtxt file and it seems to have 3 placeholders for input, named `input_1, input_2, input_3`. It seems that input_2 and input_3 are the labels you used during training. 

Regardless, I could not really find the list of your output nodes. Are you aware of the naming convention you used there?
