### ISSUE TITLE
OSError: Unable to open file

### ISSUE THREAD

**Issue by mengxiabing** [amir-abdi/keras_to_tensorflow#30]
Using TensorFlow backend.
Traceback (most recent call last):
  File "keras_to_tensorflow.py", line 114, in <module>
    net_model = load_model(weight_file_path)
  File "D:\Program Files\Anaconda3\lib\site-packages\keras\models.py", line 237,
 in load_model
    with h5py.File(filepath, mode='r') as f:
  File "D:\Program Files\Anaconda3\lib\site-packages\h5py\_hl\files.py", line 27
2, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "D:\Program Files\Anaconda3\lib\site-packages\h5py\_hl\files.py", line 92
, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (C:\Mino
nda\conda-bld\h5py_1474482825505\work\h5py\_objects.c:2705)
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (C:\Mino
nda\conda-bld\h5py_1474482825505\work\h5py\_objects.c:2663)
  File "h5py\h5f.pyx", line 76, in h5py.h5f.open (C:\Minonda\conda-bld\h5py_1474
482825505\work\h5py\h5f.c:1951)
OSError: Unable to open file (Unable to open file: name = ''model.h5'', errno =
2, error message = 'no such file or directory', flags = 0, o_flags = 0)

**Comment by amir-abdi** [comment]
The error states that the model.h5 file does not exist in the folder where weight_file_path is referring to. Make sure the model file is in the correct folder. 

Feel free to reopen the issue if there were further problems.
