### ISSUE TITLE
AttributeError: 'module' object has no attribute 'set_image_data_format'

### ISSUE THREAD

**Issue by honeywellwenjie** [amir-abdi/keras_to_tensorflow#95]
sing TensorFlow backend.
Traceback (most recent call last):
  File "keras_to_tensorflow.py", line 182, in <module>
    app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "keras_to_tensorflow.py", line 126, in main
    K.set_image_data_format('channels_last')
AttributeError: 'module' object has no attribute 'set_image_data_format'

How to fix that ?

**Comment by Syxxxxx** [comment]
Hello, are you Chinese，may I ask you some questions

**Comment by honeywellwenjie** [comment]
是,能说中文,我觉得可能是我版本的问题.

**Comment by Syxxxxx** [comment]
我想将我的一个简单的keras模型转成tensorflow模型，出现TypeError: Expected Operation, Variable, or Tensor, got 0 的问题，很苦恼

**Comment by amir-abdi** [comment]
`set_image_data_format` is well-documented here: [keras.io](https://keras.io/backend/)
Which Keras version are you using?
I wonder if you have not updated your Keras library for quite some time. Try updating it and test again.
