### ISSUE TITLE
TypeError('Expected Operation, Variable, or Tensor, got ' + str(x))

### ISSUE THREAD

**Issue by Syxxxxx** [amir-abdi/keras_to_tensorflow#96]
Traceback (most recent call last):
  File "totensor.py", line 173, in <module>
    app.run(main)
  File "C:\Users\Lenovo\Anaconda3\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\Lenovo\Anaconda3\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "totensor.py", line 116, in main
    model = load_model(FLAGS.input_model, FLAGS.input_model_json)
  File "totensor.py", line 62, in load_model
    model = keras.models.load_model(input_model_path)
  File "C:\Users\Lenovo\Anaconda3\lib\site-packages\keras\engine\saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "C:\Users\Lenovo\Anaconda3\lib\site-packages\keras\engine\saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "C:\Users\Lenovo\Anaconda3\lib\site-packages\keras\engine\saving.py", line 274, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\Users\Lenovo\Anaconda3\lib\site-packages\keras\engine\saving.py", line 627, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Users\Lenovo\Anaconda3\lib\site-packages\keras\layers\__init__.py", line 168, in deserialize
    printable_module_name='layer')
  File "C:\Users\Lenovo\Anaconda3\lib\site-packages\keras\utils\generic_utils.py", line 147, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Users\Lenovo\Anaconda3\lib\site-packages\keras\engine\sequential.py", line 302, in from_config
    model.add(layer)
  File "C:\Users\Lenovo\Anaconda3\lib\site-packages\keras\engine\sequential.py", line 166, in add
    layer(x)
  File "C:\Users\Lenovo\Anaconda3\lib\site-packages\keras\layers\recurrent.py", line 541, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "C:\Users\Lenovo\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "C:\Users\Lenovo\Anaconda3\lib\site-packages\keras\engine\base_layer.py", line 489, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\Lenovo\Anaconda3\lib\site-packages\keras\layers\recurrent.py", line 1105, in call
    initial_state=initial_state)
  File "C:\Users\Lenovo\Anaconda3\lib\site-packages\keras\layers\recurrent.py", line 682, in call
    input_length=timesteps)
  File "C:\Users\Lenovo\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 3105, in rnn
    targets=[last_output])
  File "C:\Users\Lenovo\Anaconda3\lib\site-packages\tensorflow_core\python\keras\utils\tf_utils.py", line 134, in get_reachable_from_inputs
    raise TypeError('Expected Operation, Variable, or Tensor, got ' + str(x))

How to fix that?

**Comment by stevenyesz** [comment]
comment line 23 "K.set_learning_phase(0)" can fix this problem

**Comment by Syxxxxx** [comment]
thanks. but now it has that problem.
Traceback (most recent call last):
  File "keras_to_tensorflow.py", line 182, in <module>
    app.run(main)
  File "C:\Users\Lenovo\Anaconda3\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\Lenovo\Anaconda3\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "keras_to_tensorflow.py", line 148, in main
    sess = K.get_session()
  File "C:\Users\Lenovo\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 379, in get_session
    '`get_session` is not available '
RuntimeError: `get_session` is not available when using TensorFlow 2.0.

**Comment by stevenyesz** [comment]
我也在折腾这个东西兄弟

**Comment by Syxxxxx** [comment]
这是我的微信号Syxxxxx_5991，可以向你请教交流下嘛

**Comment by stevenyesz** [comment]
ok,谈不上请教,一起摸索摸索

**Comment by SamsLogic** [comment]
How did you fix the above mentioned problem @Syxxxxx @amir-abdi ?
