### ISSUE TITLE
ypeError: mkdir() got an unexpected keyword argument 'exist_ok'

### ISSUE THREAD

**Issue by ricox78** [amir-abdi/keras_to_tensorflow#98]
Tried today to convert my h5 model but I have this:

```
sudo python keras_to_tensorflow.py --input_model="mymodel.h5" --output_model="mymodel.pb"
Using TensorFlow backend.
Traceback (most recent call last):
  File "keras_to_tensorflow.py", line 182, in <module>
    app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "keras_to_tensorflow.py", line 121, in main
    Path(output_model).parent.mkdir(parents=True, exist_ok=True)
TypeError: mkdir() got an unexpected keyword argument 'exist_ok'
```
Thank's for any help

**Comment by jayveedee** [comment]
Same error. Did you ever get it fixed?

**Comment by OceanWong1991** [comment]
use Python3

**Comment by markfilan** [comment]
In some cases, if you are using older versions of Python, you will get the [mkdir](http://net-informations.com/python/pro/dir.htm)() got an unexpected keyword argument 'exists_ok' exception.

If you are using Python 3.5 or above, use pathlib.Path.mkdir:

```
from pathlib import Path
Path("/myDir/nested").mkdir(parents=True, exist_ok=True)
print("done")
```

**Comment by amir-abdi** [comment]
According to the [documentation](https://docs.python.org/3/library/os.html#os.makedirs), `exist_ok` parameter was added in python 3.2.
> New in version 3.2: The exist_ok parameter.
