### ISSUE TITLE
ValueError: Unknown initializer: f

### ISSUE THREAD

**Issue by zyyhl** [amir-abdi/keras_to_tensorflow#99]
E1111 14:35:28.563664 140541594945280 keras_to_tensorflow.py:85] Input file specified only holds the weights, and not the model definition. Save the model using model.save(filename.h5) which will contain the network architecture as well as its weights. If the model is saved using model.save_weights(filename), the flag input_model_json should also be set to the architecture which is exported separately in a json format. Check the keras documentation for more details (https://keras.io/getting-started/faq/)
Traceback (most recent call last):
  File "keras_to_tensorflow.py", line 172, in <module>
    app.run(main)
  File "/scratch/workspace/anaconda2/lib/python2.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/scratch/workspace/anaconda2/lib/python2.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "keras_to_tensorflow.py", line 118, in main
    model = load_models(FLAGS.input_model, FLAGS.input_model_json)
  File "keras_to_tensorflow.py", line 94, in load_models
    raise wrong_file_err
ValueError: Unknown initializer: f

My .h5 file contains the model structure and weights. Can you help me see what is wrong?

**Comment by cydawn** [comment]
I just meet this problem. Do you fix it？ @zyyhl
